[workspace]

members = [ "d01", "d02", "d03", "d04", "d05", "d06", "d07", "d08", "d09", "d10", "d11", "d12",
    "utils",
]
resolver = "2"

[workspace.dependencies]
itertools = "^0.13"
fxhash = "^0.2"
num-complex = "^0.4"
regex = "^1"
